package generate

import (
	"fmt"
	"sort"
	"strings"

	"github.com/fow830/ratchet/pkg/tokens"
)

// Output is a generated file path and body.
type Output struct {
	Path string
	Body string
}

// Outputs returns all token-gen artifacts for cfg.
func Outputs(cfg tokens.Config) []Output {
	outs := []Output{
		{Path: tokens.EnvExampleRel, Body: RenderEnvExample(cfg)},
		{Path: tokens.DirGenerated + "/" + tokens.ToolName + "_layers.go", Body: RenderLayersGo(cfg)},
		{Path: tokens.DirGenerated + "/docker-compose." + tokens.ToolName + ".yml", Body: RenderCompose(cfg)},
		{Path: tokens.DirGenerated + "/Dockerfile." + tokens.ToolName, Body: RenderDockerfile(cfg)},
	}
	if cfg.Codegen.SQLCPath != "" || cfg.Preset == tokens.PresetVitek {
		outs = append(outs, Output{Path: tokens.DirGenerated + "/sqlc." + tokens.ToolName + ".yaml", Body: RenderSQLC(cfg)})
	}
	return outs
}

// RenderEnvExample renders environment template from SSOT.
func RenderEnvExample(cfg tokens.Config) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# Generated from %s — do not edit manually\n", tokens.ConfigFileName)
	fmt.Fprintf(&b, "RATCHET_MODULE=%s\n", cfg.Module)
	fmt.Fprintf(&b, "RATCHET_PROFILE=%s\n", cfg.Profile)
	if cfg.Preset != "" {
		fmt.Fprintf(&b, "RATCHET_PRESET=%s\n", cfg.Preset)
	}
	return b.String()
}

// RenderLayersGo renders Go constants for configured layers.
func RenderLayersGo(cfg tokens.Config) string {
	type pair struct{ suffix, layer string }
	var pairs []pair
	for suffix, layer := range cfg.Layers {
		pairs = append(pairs, pair{suffix, layer})
	}
	sort.Slice(pairs, func(i, j int) bool { return pairs[i].layer < pairs[j].layer })

	var b strings.Builder
	b.WriteString("// Code generated by tokensgen; DO NOT EDIT.\n")
	b.WriteString("package generated\n\n")
	b.WriteString("const (\n")
	b.WriteString("\tModule = \"" + cfg.Module + "\"\n")
	seen := map[string]struct{}{}
	for _, p := range pairs {
		if _, dup := seen[p.layer]; dup {
			continue
		}
		seen[p.layer] = struct{}{}
		id := strings.ToUpper(p.layer[:1]) + p.layer[1:]
		fmt.Fprintf(&b, "\tLayer%s = %q\n", id, p.layer)
	}
	b.WriteString(")\n")
	return b.String()
}

// RenderCompose renders a minimal compose stub from SSOT.
func RenderCompose(cfg tokens.Config) string {
	dockerfile := tokens.DirGenerated + "/Dockerfile." + tokens.ToolName
	return fmt.Sprintf(`# Generated from %s — do not edit manually
services:
  app:
    build:
      context: .
      dockerfile: %s
    environment:
      RATCHET_MODULE: %q
      RATCHET_PROFILE: %q
`, tokens.ConfigFileName, dockerfile, cfg.Module, cfg.Profile)
}

// RenderDockerfile renders a minimal Go Dockerfile stub.
func RenderDockerfile(cfg tokens.Config) string {
	return fmt.Sprintf(`# Generated from %s — do not edit manually
FROM %s AS build
WORKDIR /src
COPY . .
RUN go build -o /out/app ./...

FROM %s
COPY --from=build /out/app /app
ENTRYPOINT ["/app"]
`, tokens.ConfigFileName, tokens.DockerGoImage, tokens.DockerRuntimeImage)
}

// RenderSQLC renders a minimal sqlc config stub.
func RenderSQLC(cfg tokens.Config) string {
	out := tokens.DirInternal + "/" + tokens.LayerRepository + "/sqlc"
	return fmt.Sprintf(`# Generated from %s — do not edit manually
version: "2"
sql:
  - engine: "postgresql"
    queries: "db/queries"
    schema: "db/migrations"
    gen:
      go:
        package: "sqlc"
        out: %q
`, tokens.ConfigFileName, out)
}
